name: Sync with template

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Template Sync
        uses: AndreasAugustin/actions-template-sync@v2
        with:
          source_repo_path: "AstroNvim/template"
          upstream_branch: "main"
          github_token: ${{ secrets.GITHUB_TOKEN }}
