name: Sync with template

on:
  push:
    branches:
      - main
  # cronjob trigger
  schedule:
    - cron:  "0 0 1 * *"
  # manual trigger
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Template Sync
        uses: AndreasAugustin/actions-template-sync@v2
        with:
          source_repo_path: "AstroNvim/template"
          upstream_branch: "main"
          git_user_name: gpproton
          git_user_email: me@godwin.dev
          github_token: ${{ secrets.GITHUB_TOKEN }}
